<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://example.com/bpel/userManagement"
            xmlns:tns="http://example.com/bpel/userManagement">

    <xsd:element name="manageUserRequest">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="operation" type="xsd:string"/>
                <xsd:element name="username" type="xsd:string"/>
                <xsd:element name="password" type="xsd:string"/>
                <xsd:element name="nickname" type="xsd:string" minOccurs="0"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="manageUserResponse">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="result" type="xsd:string"/>
                <xsd:element name="status" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>